// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddStopwatch(arg1, arg2, arg3) {
  return window['go']['main']['App']['AddStopwatch'](arg1, arg2, arg3);
}

export function DeleteStopwatch(arg1) {
  return window['go']['main']['App']['DeleteStopwatch'](arg1);
}

export function GetStopwatch(arg1) {
  return window['go']['main']['App']['GetStopwatch'](arg1);
}

export function GetStopwatchIds() {
  return window['go']['main']['App']['GetStopwatchIds']();
}

export function GetUserColorTheme() {
  return window['go']['main']['App']['GetUserColorTheme']();
}

export function HasStopwatch(arg1) {
  return window['go']['main']['App']['HasStopwatch'](arg1);
}

export function SetUserColorTheme(arg1) {
  return window['go']['main']['App']['SetUserColorTheme'](arg1);
}

export function UpdateStopwatchTime(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdateStopwatchTime'](arg1, arg2, arg3);
}
