// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddStopwatch(arg1:string,arg2:string,arg3:number):Promise<boolean>;

export function DeleteStopwatch(arg1:string):Promise<boolean>;

export function GetStopwatch(arg1:string):Promise<main.StopwatchData>;

export function GetStopwatchIds():Promise<Array<string>>;

export function GetUserColorTheme():Promise<main.ColorTheme>;

export function HasStopwatch(arg1:string):Promise<boolean>;

export function SetUserColorTheme(arg1:main.ColorTheme):Promise<void>;

export function UpdateStopwatchTime(arg1:string,arg2:boolean,arg3:number):Promise<void>;
