// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetUserColorTheme() {
  return window['go']['main']['App']['GetUserColorTheme']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function SetUserColorTheme(arg1) {
  return window['go']['main']['App']['SetUserColorTheme'](arg1);
}
