// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetUserColorTheme():Promise<main.ColorTheme>;

export function SetUserColorTheme(arg1:main.ColorTheme):Promise<void>;
